### ISSUE TITLE
document/recommend "return, but continue in parallel" usage?

### ISSUE THREAD

**Issue by inexorabletash** [garykac/procspec#13]
Current:

1. Let _p_ be a new Promise
2. Run the following substeps in parallel:
  a. Let _foo_ be something awesome, with sprinkles.
  b. Resolve _p_ with foo
3. Return _p_

I notice HTML uses:

1. Let _p_ be a new Promise
2. Return _p_, but continue running these steps in parallel.
3. Let _foo_ be something awesome, with sprinkles.
4. Resolve _p_ with foo

I don't know when this usage arrived (over a year ago?) but it seems to have slightly lower cognitive overhead. This would e.g. dramatically reduce the amount of indentation in Service Workers. Maybe @annevk or @domenic can comment on the preference for this style?

**Comment by annevk** [comment]
Current is better. It's weird for algorithms to continue running after you return.

**Comment by inexorabletash** [comment]
Groovy. I'll close this out then, and file a bug against HTML
